Update featurization.yaml

diff --git a/.github/workflows/featurization.yaml b/.github/workflows/featurization.yaml
--- a/.github/workflows/featurization.yaml
+++ b/.github/workflows/featurization.yaml
@@ -42,13 +42,14 @@ jobs:
 
     - name: Download file
       id: download
+      env:
+        GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
-        cat match.txt
         brew install wget
         file=$(cat match.txt)
         file=$(echo $file | sed 's/\.zipLICENSE/\.zip/g')
         echo $file
-        wget -O task.zip $file || echo "::set-output name=failed::true"
+        wget --header="Authorization: token $GH_TOKEN" $file -O task.zip || echo "::set-output name=failed::true"
         fi
       shell: bash
         
