Update featurization.yaml

diff --git a/.github/workflows/featurization.yaml b/.github/workflows/featurization.yaml
--- a/.github/workflows/featurization.yaml
+++ b/.github/workflows/featurization.yaml
@@ -42,13 +42,11 @@ jobs:
 
     - name: Download file
       id: download
-      env:
-        PAT: ${{ secrets.PAT }}
       run: |
         file=$(cat match.txt)
         file=$(echo $file | sed 's/\.zipLICENSE/\.zip/g')
         echo $file
-        wget --header='Authorization: token ${{ secrets.PAT }}' --header='Accept: application/vnd.github.v3.raw' -O task.zip $file || echo "::set-output name=failed::true"
+        wget -O task.zip $file || echo "::set-output name=failed::true"
         
     - name: Send message if download failed
       uses: actions/github-script@v5
